feat(vqb): added step date to text + unit tests
ToucanToco/weaverbird pull request #1003
Opened 2021-08-19 14:53 UTC by Sanix-Darker

# What :
- vqb updates
    - added Date To Text step
![from_date_2](https://user-images.githubusercontent.com/22576758/130090798-86d654ad-0a87-4f07-bafd-1acc59c0425b.gif)

2021-08-19 14:54 UTC, Sanix-Darker commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2) [Snowflake SQL VQB] - Convert Date to text Step](https://trello.com/c/CSySxQcK/1169-2-snowflake-sql-vqb-convert-date-to-text-step)

2021-08-19 15:37 UTC, raphaelvignes submitted a review, later dismissed
Du coup tu fais les deux steps de date dans cette PR ? Je pense que c'est OK. 
Juste une petite rmq, je pense que tu mettre les tests de ta fonction de formattage de date à un autre endroit (cf le commentaire).

En fait tu as rebase j'imagine...

2021-08-19 15:37 UTC, raphaelvignes commented on server/weaverbird/backends/sql_translator/steps/__init__.py
> +from .fromdate import translate_fromdate
Pourquoi on l'ajoute dans cette PR ?

2021-08-19 15:37 UTC, raphaelvignes commented on server/weaverbird/backends/sql_translator/steps/__init__.py
> +    'fromdate': translate_fromdate,
idem ?

2021-08-19 15:37 UTC, raphaelvignes commented on server/tests/steps/sql_translator/test_snowflake_date_format.py
> +from weaverbird.backends.sql_translator.steps.utils.query_transformation import (
Je pense que tu peux mettre ces tests dans: 
`server/tests/steps/sql_translator/utils/test_query_transformation.py`

2021-08-20 10:49 UTC, raphaelvignes requested changes
Merci pour cette nouvelle step ! 
Une petite remarque sur le type à utiliser lors de la mise à jour.

2021-08-20 10:49 UTC, raphaelvignes commented on server/weaverbird/backends/sql_translator/steps/fromdate.py
> +    query.metadata_manager.change_type(step.column, 'text')
```suggestion
    query.metadata_manager.change_type(step.column, 'str')
```
La liste des types que l'on utilise est dispo ici: https://github.com/ToucanToco/toucan-connectors/blob/9ee0f48448e17b67b7def559e994ff65148b5b4c/toucan_connectors/snowflake_common.py#L14

2021-08-20 11:16 UTC, Sanix-Darker commented on server/weaverbird/backends/sql_translator/steps/fromdate.py
> +    query.metadata_manager.change_type(step.column, 'text')
updated !

2021-08-20 11:50 UTC, raphaelvignes approved these changes

2021-08-20 12:06 UTC, merged