feat(vqb): TOP-N rows
ToucanToco/weaverbird pull request #1014
Opened 2021-08-23 11:22 UTC by Sanix-Darker

# What:
   - vqb steps:
       - added top-n ros step
       - added tests for the step
   
# ScreenShot
![top-n](https://user-images.githubusercontent.com/22576758/130439216-eabb6d73-2a2f-4d88-9028-55d52d784656.gif)

2021-08-23 11:42 UTC, Sanix-Darker commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2) [Snowflake SQL VQB] - Top N rows step](https://trello.com/c/lxERrYJ5/1178-2-snowflake-sql-vqb-top-n-rows-step)

2021-08-23 12:01 UTC, f-bb-toucantoco requested changes
- UT si il n'y a pas de group sur les columns
- fichier de fixture

2021-08-23 12:07 UTC, f-bb-toucantoco requested changes

2021-08-23 12:07 UTC, f-bb-toucantoco commented on server/tests/steps/sql_translator/test_top.py
> +        assert query.selection_query == 'SELECT TOTO, RAICHU, FLORIZARRE FROM TOPN_STEP_1'
Pas trop d'intérêt de tester cet assert ?

2021-08-23 12:07 UTC, f-bb-toucantoco commented on server/weaverbird/backends/sql_translator/steps/top.py
> +    for c in [
Nous pouvons peut-être déporter cette logique directement dans la gestion des metadatas
Au lieu de passer une simple colonne, nous passons une List de colonne. Cela permet d'enrichir l'objet et d'éviter de reproduire les boucles et réduire ainsi les modifications avant le passage à l'objet Table et l'objet Column

2021-08-23 13:17 UTC, f-bb-toucantoco requested changes

2021-08-23 13:28 UTC, Sanix-Darker commented on server/tests/steps/sql_translator/test_top.py
> +        'RAICHU FROM SELECT_STEP_0 GROUP BY RAICHU ORDER BY RAICHU asc) '
Sans colonnes, je me disais qu'on devait group by la colonne du rank `step.rank_on` conf : [13](https://github.com/ToucanToco/weaverbird/blob/master/server/weaverbird/pipeline/steps/top.py#L13) ,
🤔 Mais tout bien reflechis, c'est vrai qu'il nintervient pas vraiment dans le Group BY...

2021-08-24 09:25 UTC, f-bb-toucantoco requested changes

2021-08-24 09:25 UTC, f-bb-toucantoco commented on server/tests/backends/sql_translator/test_snowflake_translator_steps.py
> +    result.columns = [c.upper() for c in result.columns]
Tu change le comportement attendu dans ton test
Le result que tu récupère doit déjà avoir les colonnes au bon format, si tu modifie dans ton test, il est impossible de garantir le résultat récupéré sur du e2e et ça veut dire qu'on ne fait finalement plus un e2e

2021-08-24 09:25 UTC, f-bb-toucantoco commented on server/tests/backends/sql_translator/test_sql_translator_steps.py
> +        try:
Pourquoi cette exception ?
il me semble que docker_client.images.list() retourne toujours une liste même si elle est vide ?

2021-08-24 09:25 UTC, f-bb-toucantoco commented on server/weaverbird/backends/sql_translator/steps/top.py
> +    query_name = f'TOPN_STEP_{index}'
Pourquoi TOPN alors que la step s'appelle top ? 
Un seul nom serait bien

2021-08-24 09:25 UTC, f-bb-toucantoco commented on server/weaverbird/backends/sql_translator/types.py
> +        column_names: Union[str, List[str]] = "all-columns",
Je pense que le fait d'utiliser un Union plutôt que d'envoyer la liste des colonnes complexifie la façon dont le sujet est traité.
Mais ne t'embête pas à rechanger car il y a le nouvel objet Metadata qui va changer ça

2021-08-24 11:30 UTC, Sanix-Darker commented on server/tests/backends/sql_translator/test_sql_translator_steps.py
> +        try:
Une erreur survenait chez moi en local et chez @raphaelvignes si je ne me trompes pas(et s'il s'agissait bien de cela chez lui) quand a la presence d'une image (la premiere) que retournait la lib python `docker` depuis `docker_client.images.list()` mais avec dans le tableau `tag` aucune valeur.... je fais ce `try-except` pour sauter ce soucis particulier, sinon le make test ne marche pas en local chez moi !

2021-08-24 11:33 UTC, Sanix-Darker commented on server/weaverbird/backends/sql_translator/types.py
> +        column_names: Union[str, List[str]] = "all-columns",
ok

2021-08-24 11:33 UTC, Sanix-Darker commented on server/weaverbird/backends/sql_translator/steps/top.py
> +    query_name = f'TOPN_STEP_{index}'
updated !

2021-08-24 12:39 UTC, Sanix-Darker commented on server/tests/backends/sql_translator/test_snowflake_translator_steps.py
> +    result.columns = [c.upper() for c in result.columns]
True !

2021-08-24 13:05 UTC, f-bb-toucantoco approved these changes

2021-08-24 13:05 UTC, f-bb-toucantoco commented on server/tests/backends/sql_translator/test_sql_translator_steps.py
> +        try:
👍

2021-08-24 13:07 UTC, merged