feat(vqb): added uniquegroups step
ToucanToco/weaverbird pull request #1020
Opened 2021-08-24 14:12 UTC by Sanix-Darker

# What:
   - vqb steps:
       - [x] added uniquegroup step
       - [x] added tests for the step (normal + json)
   
# ScreenShot
![Peek 2021-08-24 13-19](https://user-images.githubusercontent.com/22576758/130632162-16bf4a68-6af6-4352-b8e6-c98ea5718160.gif)

2021-08-24 14:47 UTC, raphaelvignes requested changes
Merci pour cette nouvelle step ! 
Je ne suis pas sur de comprendre pourquoi on utilise upper & lower.

2021-08-24 14:47 UTC, raphaelvignes commented on server/weaverbird/backends/sql_translator/steps/uniquegroups.py
> +            group_by_query += (" GROUP BY " if index == 0 else ", ") + gb
Ta syntaxe est ok. 
Je pense qu'on peut aussi utiliser:
`group_by_query = f" GROUP BY {', '.join([gb for gb in step.on])}  "`
A la place des lignes 41 & 42

2021-08-24 14:47 UTC, raphaelvignes commented on server/weaverbird/backends/sql_translator/steps/uniquegroups.py
> +            all_except=([c.upper() for c in step.on] + [c.lower() for c in step.on])
Pourquoi on utilise à nouveau des `upper()` & `lower()`  ?

2021-08-24 14:47 UTC, raphaelvignes commented on server/weaverbird/backends/sql_translator/steps/uniquegroups.py
> +        # We remove superflues columns
```suggestion
        # We remove unnecessary columns
```

2021-08-24 15:53 UTC, raphaelvignes approved these changes

2021-08-24 15:57 UTC, merged

2021-08-25 06:57 UTC, Sanix-Darker commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2) [Snowflake SQL VQB] - Unique Group step](https://trello.com/c/KBbXlG3L/1179-2-snowflake-sql-vqb-unique-group-step)