feat(vqb): added step date extract
ToucanToco/weaverbird pull request #1044
Opened 2021-08-31 12:05 UTC by Sanix-Darker

# What
- VQB snowflake :
    - weaverbird backend :
        - [x] added step date extract
        - [x] added unit tests
        - [x] added fixtures tests
   - weaverbird frontend : 
        - [x] added dateextract to snowflake translator

# Overview
![date_extract](https://user-images.githubusercontent.com/22576758/131499197-da716a1f-4fa8-49ea-8ea6-352f79b11258.gif)

2021-08-31 12:13 UTC, Sanix-Darker commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Snowflake SQL VQB] - Date extraction Step (3)](https://trello.com/c/T9v2Qtlo/1176-snowflake-sql-vqb-date-extraction-step-3)

2021-09-01 08:12 UTC, raphaelvignes requested changes
Merci pour cette nouvelle step ! :fire: 
Je pense qu'il faut ajouter quelques tests. 
La logique du choix de fonction à appliquer me semble pas mal.

2021-09-01 08:12 UTC, raphaelvignes commented on server/weaverbird/backends/sql_translator/steps/dateextract.py
> +            to_extract_string += ", "
tu peux faire la même chose avec `', '.join([ ])`

2021-09-01 08:12 UTC, raphaelvignes commented on server/tests/steps/sql_translator/test_dateextract.py
> +
Est-ce que tu peux faire un test sur les metadata obtenues aussi ? :pray:

2021-09-01 08:12 UTC, raphaelvignes commented on server/tests/steps/sql_translator/test_dateextract.py
> +
Est-ce que tu peux faire un test sur les metadata obtenues aussi ? :pray:

2021-09-01 08:12 UTC, raphaelvignes commented on server/tests/steps/sql_translator/test_dateextract.py
> +    assert query.query_name == 'DATEEXTRACT_STEP_1'
Idem ici ?

2021-09-01 08:12 UTC, raphaelvignes commented on server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
> +def get_query_for_date_extract(
Fonction à tester !

2021-09-01 09:32 UTC, Sanix-Darker commented on server/weaverbird/backends/sql_translator/steps/dateextract.py
> +            to_extract_string += ", "
updated !

2021-09-01 09:32 UTC, Sanix-Darker commented on server/tests/steps/sql_translator/test_dateextract.py
> +
updated !

2021-09-01 09:32 UTC, Sanix-Darker commented on server/tests/steps/sql_translator/test_dateextract.py
> +
updated !

2021-09-01 09:32 UTC, Sanix-Darker commented on server/tests/steps/sql_translator/test_dateextract.py
> +    assert query.query_name == 'DATEEXTRACT_STEP_1'
updated !

2021-09-01 09:32 UTC, Sanix-Darker commented on server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
> +def get_query_for_date_extract(
updated !

2021-09-01 11:22 UTC, raphaelvignes approved these changes
Merci pour la prise en compte des remarques :pray: 
Une petite release front & back à faire :)

2021-09-01 12:28 UTC, merged