feat(vqb): added concatenate step + unittests
ToucanToco/weaverbird pull request #1048
Opened 2021-09-01 13:41 UTC by Sanix-Darker

# What
- VQB snowflake concatenate step
     - [ ] unittest
     - [ ] fixtures tests
     - [ ] concatenate step
     
# Overview

2021-09-01 13:59 UTC, Sanix-Darker commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Snowflake SQL VQB] - Concatenate Step (2)](https://trello.com/c/syxzBUOZ/1200-snowflake-sql-vqb-concatenate-step-2)

2021-09-02 06:13 UTC, raphaelvignes requested changes
Super merci pour cette step ! 
Est-ce que tu peux ajouter la fixture pour le test d'intégration stp ? :pray:

2021-09-02 06:13 UTC, raphaelvignes commented on server/tests/steps/sql_translator/test_concatenate.py
> +def test_translate_simple_concatenante(query):
```suggestion
def test_translate_simple_concatenate(query):
```

2021-09-02 07:15 UTC, raphaelvignes commented on server/tests/steps/sql_translator/test_concatenate.py
> +def test_translate_simple_concatenante(query):
woops bien vu, merci ;)

2021-09-02 07:16 UTC, raphaelvignes approved these changes

2021-09-02 07:35 UTC, merged