fix(vqb): snowflake granularity fixes on aggregate, top-n-rows + huge refactos + fixtures/unit tests
ToucanToco/weaverbird pull request #1062
Opened 2021-09-08 11:18 UTC by Sanix-Darker

# What
- Snowflake granularity fixes on GroupBy :
    - [ ] aggregate step
        - [ ] granularity behaviour fixes
            - [ ] first
            - [ ] last
            - [ ] max
            - [ ] min
            - [ ] sum
            - [ ] avg
            - [ ] count
            - [ ] count-distinct
        - [ ] fixtures tests
        - [ ] unit tests
        - [ ] refactor
    - [x] top-n-rows step
        - [x] granularity behaviour fix
        - [x] fixtures tests
        - [x] unit tests
    - [x] rank step
        - [x] refacto
        - [x] fixtures tests
        - [x] unit tests
        
# FIXES DEMOS :
## top-n-rows step
### Before fix

### After fix

----
## aggregate step
### Before fix

### After fix

⚠️ **Note**  : Please pay a lot of attention on the PR, these change were a little bit complexe to implement/refactor, and as am a human i may made some errors that can break things in the future ! 🙏🏾

2021-09-10 10:34 UTC, raphaelvignes commented on server/weaverbird/backends/sql_translator/steps/rank.py
> +            generate_query_by_keeping_granularity(
:+1:

2021-09-10 10:37 UTC, raphaelvignes commented on server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
> +                break
Pas sur que ce soit ouf d'utiliser une boucle avec un break. 
Il y'a peut être moyen de ré écrire ça.

2021-09-10 10:38 UTC, raphaelvignes commented on server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py
> +def generate_query_by_keeping_granularity(
Je pense qu'il va falloir ajouter des tests unitaires sur cette fonction pour être bien sur d'obtenir les résultats attendus.

2021-09-10 10:39 UTC, raphaelvignes reviewed
Merci d'avoir pris ce chantier ! 
Il va falloir qu'on teste bien les fonctions ajoutées en utils et les steps modifiées avec des tests unitaires + tests d'intégration.

2021-09-15 07:01 UTC, Sanix-Darker commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Snowflake SQL VQB] - Aggregate Step/Group by/top rows/... - Keep Granularity Option (5) [8]](https://trello.com/c/L7bJjPkg/1138-snowflake-sql-vqb-aggregate-step-group-by-top-rows-keep-granularity-option-5-8)

2021-09-15 14:31 UTC, f-bb-toucantoco requested changes
A dispo pour discuter autour de ce morceau de code.
Je pense que même pour une version "non propre" du VQB, ça reste trop complexe
Si quelqu'un doit reprendre le sujet, remettre au propre ou corriger un bug, ça sera presque impossible

2021-09-15 14:31 UTC, f-bb-toucantoco commented on server/tests/steps/sql_translator/test_aggregate.py
> +        == "WITH SELECT_STEP_0 AS (SELECT * FROM products), AGGREGATE_STEP_1 AS (SELECT first_Label, category FROM ("
double quote are not compliant with Toucan compliance format / lint

2021-09-15 14:31 UTC, f-bb-toucantoco commented on server/tests/steps/sql_translator/test_aggregate.py
> -        == 'WITH SELECT_STEP_0 AS (SELECT * FROM products), AGGREGATE_STEP_1 AS (SELECT first_Label FROM (SELECT '
double quote are not compliant with Toucan compliance format / lint

2021-09-15 14:31 UTC, f-bb-toucantoco commented on server/tests/steps/sql_translator/test_aggregate.py
> +        "Label AS last_Label, ROW_NUMBER() OVER (ORDER BY Label) AS R FROM SELECT_STEP_0 QUALIFY R = 1))"
C'est vraiment pas top de supprimer le DESC, un ORDER devrait toujours par défaut être marqué en ASC / DESC
Cela n'est pas utile pour la requête, c'est côté lisibilité que c'est utile

2021-09-15 14:31 UTC, f-bb-toucantoco commented on server/weaverbird/backends/sql_translator/steps/rank.py
> +        order_by_query = f"ORDER BY {step.new_column_name}, {', '.join(step.groupby)}"
Comme dit plus haut, ça serait bien d'avoir ASC / DESC pour définir / rappeler le sens du tri

2021-09-15 14:31 UTC, f-bb-toucantoco commented on server/weaverbird/backends/sql_translator/steps/top.py
> +            f"{query_name}_ALIAS ORDER BY {', '.join(step.groups)}"
same : ASC / DESC

2021-09-15 14:31 UTC, f-bb-toucantoco commented on server/weaverbird/backends/sql_translator/steps/utils/aggregation.py
> +    for aggregation in step.aggregations:
Ce bout de code a l'air complexe, ça serait cool d'avoir un peu de commentaire pour ne pas oublier ce qui a été fait et pour quelle raison.

De même je pense qu'il y a possibilité de réduire la complexité en divisant le code un peu autrement. Le mieux c'est peut-être directement d'en discuter pour voir ce qui est faisable.

2021-09-16 15:35 UTC, f-bb-toucantoco approved these changes

2021-09-16 16:13 UTC, merged