feat: add metadata for pypi
ToucanToco/weaverbird pull request #1347
Opened 2022-06-03 16:06 UTC by Sanix-Darker

## WHAT

Just added metadatas for pypi

2022-06-09 07:54 UTC, PrettyWood requested changes
thanks

2022-06-09 07:54 UTC, PrettyWood commented on server/setup.cfg
> +authors = ["Toucantoco <tokar@gmail.com>"]
```suggestion
authors = ["Toucan Toco <dev@toucantoco.com>"]
```

2022-06-09 07:54 UTC, PrettyWood commented on server/setup.cfg
> +license = "BSD 3-Clause"
```suggestion
license = "BSD-3-Clause"
```

2022-06-10 11:58 UTC, fspot commented
Changes included in https://github.com/ToucanToco/weaverbird/pull/1348 :ok_hand:

2022-06-10 11:58 UTC, closed without merging