fix(Formula AST): Be more permissive on column names
ToucanToco/weaverbird pull request #1467
Opened 2022-09-13 15:03 UTC by lukapeschke

Allow column names to contain operators and extra whitespaces.

An implementation change is required for that: We now store the start and end position of bracket
delimiters and consider everything in-between to be the column name (meaning we don't strip whitespace
at the start and end anymore, nor do we check the validity of the tokens in the column name).

TCTC-3866

2022-09-13 15:04 UTC, lukapeschke commented on server/src/weaverbird/pipeline/formula_ast/eval.py
> +            # NOTE: position is expressed as a (posLine, posColumn) tupple. We assume that the
```suggestion
            # NOTE: position is expressed as a (posLine, posColumn) tuple. We assume that the
```

2022-09-13 16:32 UTC, Sanix-Darker approved these changes
LGTM !

2022-09-13 16:32 UTC, Sanix-Darker commented on server/src/weaverbird/pipeline/formula_ast/eval.py
> +            start = prev_token.end[1]
👍🏽

2022-09-14 10:33 UTC, PrettyWood requested changes

2022-09-14 10:33 UTC, PrettyWood commented on server/CHANGELOG.md
> +  (allow columns to include dashes)
Or quotes, white spaces...

2022-09-14 10:33 UTC, PrettyWood commented on server/src/weaverbird/backends/pandas_executor/steps/utils/formula.py
> +        expr = unquote_string(expr, escape_quotes=False)
Deserves a comment

2022-09-14 12:46 UTC, PrettyWood approved these changes

2022-09-14 12:47 UTC, merged