feat: Allow all steps to be populated with camelCase fields
ToucanToco/weaverbird pull request #1559
Opened 2022-10-27 08:28 UTC by lukapeschke

2022-10-27 08:28 UTC, lukapeschke commented
depends on #1556

2022-10-27 08:32 UTC, PrettyWood reviewed
Why not just add alias_generator in the Config of BaseStep and that's it

2022-10-27 08:37 UTC, lukapeschke commented
> Why not just add alias_generator in the Config of BaseStep and that's it

Because there's a bit more that needs to be solved, such as `IfThenElseStep`, which contains an `IfThenElse` model that had its own config. There's a lot of noise from #1556 here though, it should be more readable once #1556 is merged :sweat_smile:

2022-10-28 08:44 UTC, PrettyWood requested changes
LGTM otherwise thanks!

2022-10-28 08:44 UTC, PrettyWood commented on server/src/weaverbird/pipeline/steps/evolution.py
> +    index_columns: TemplatedVariable | list[TemplatedVariable]
```suggestion
    index_columns: TemplatedVariable | list[TemplatedVariable] = Field(default_factory=list)
```

2022-10-28 08:49 UTC, PrettyWood approved these changes

2022-10-28 09:05 UTC, merged