refactor(ui): Make all step attributes camelCase
ToucanToco/weaverbird pull request #1629
Opened 2022-11-30 13:54 UTC by lukapeschke

Signed-off-by: Luka Peschke <luka.peschke@toucantoco.com>

2022-11-30 14:52 UTC, PrettyWood requested changes

2022-11-30 14:52 UTC, PrettyWood commented on ui/src/lib/labeller.ts
> +  return obj.newColumn ? obj.newColumn : obj.newColumn;
```suggestion
  return obj.newColumn;
```

2022-11-30 14:56 UTC, lukapeschke commented on ui/src/lib/labeller.ts
> +  return obj.newColumn ? obj.newColumn : obj.newColumn;
Ah yes bien vu on va pouvoir complètement tej cette fonction d'ailleurs

2022-11-30 17:06 UTC, PrettyWood requested changes

2022-11-30 17:06 UTC, PrettyWood commented on ui/src/lib/translators/mongo.ts
> +    mongoPipeline.push({ $match: { [step.valueColumn_name]: { $ne: null } } });
```suggestion
    mongoPipeline.push({ $match: { [step.valueColumnName]: { $ne: null } } });
```
?

2022-12-06 08:49 UTC, alice-sevin approved these changes

2022-12-06 09:06 UTC, PrettyWood approved these changes

2022-12-06 09:59 UTC, merged