feat(codeEditor): use a specific config in a codeEditorWidget
ToucanToco/weaverbird pull request #626
Opened 2020-09-01 09:59 UTC by alice-sevin

Before: `setCodeEditor` added a unique codeEditor used for all the app.
After: 
- `setCodeEditors`, a new method, allow to provide multiple config each associated to a lang key.
- Optionnaly, the default lang can be provided in `setCodeEditors` and will be used for every codeEditor as default
- CodeEditorWidget can now take a lang param: use selected lang config if provided `setCodeEditors` values. Otherwise, use default code editor one.

2020-09-01 11:07 UTC, alice-sevin commented
![](https://github.trello.services/images/mini-trello-icon.png) [(5) ETQD, je peux utiliser un JSEditor dans weaverbird](https://trello.com/c/3Zt3WIPX/776-5-etqd-je-peux-utiliser-un-jseditor-dans-weaverbird)

2020-09-01 11:47 UTC, erenard requested changes
Merci pour ce dev, par contre je pense qu'on devrait se conformer au camelCase pour les membres des composants.

2020-09-01 11:47 UTC, erenard commented on src/components/stepforms/widgets/CodeEditorWidget.vue
> +  CodeEditor: CustomCodeEditor = CodeEditor;
```suggestion
  codeEditor: CustomCodeEditor = CodeEditor;
```
C'est important de différencier un champ `data` d'un import.

2020-09-01 11:47 UTC, erenard commented on src/components/stepforms/widgets/CodeEditorWidget.vue
> +  CodeEditor: CustomCodeEditor = CodeEditor;
Même si derrière c'est un switch sur un type d'Éditeur

2020-09-01 11:47 UTC, davinov reviewed
Thanks for working on this!
I don't really see the value of keeping `CodeEditor` and `setCodeEditor`. Wouldn't it be easier to just replace it by `AvailableCodeEditors` everywhere?
This means a slight change of external API, but as it's only used in Toucan's project for now and we're still in 0.x, it's OK to change this API.

2020-09-01 11:47 UTC, davinov commented on playground/app.js
> +    },
Maybe we can avoid duplicating these two by creating a small function:
```js
function codeEditorForLang(lang) {
  return {
    props: ['value', 'placeholder'],
    render(createElement) {
      return createElement('textarea', {
        domProps: {
          value: this.value,
          placeholder: `OMG I have to write code in ${lang} in here`,
        },
        attrs: {
          type: 'text',
        },
        on: {
          input: event => {
            this.$emit('input', event.target.value);
          },
          blur: event => {
            this.$emit('blur');
          },
          focus: event => {
            this.$emit('focus');
          },
        },
      });
    };
}
```
and use it for both elements

2020-09-01 15:00 UTC, erenard approved these changes

2020-09-02 08:49 UTC, davinov approved these changes
Thanks :)

I prefer the approach by lang as it paves the way for advanced translators ui customization, for example the Mongo translator could say its custom step needs a json editor and the Js translator needs a Js one.

:+1:

2020-09-02 09:44 UTC, merged