Pandas percentage step
ToucanToco/weaverbird pull request #713
Opened 2020-11-05 13:11 UTC by luc-leonard

2020-11-05 14:08 UTC, fspot commented on server/weaverbird/steps/percentage.py
> +    new_column_name: ColumnName = Field(alias='newColumnName', default=None)
```suggestion
    new_column_name: Optional[ColumnName] = Field(alias='newColumnName', default=None)
```

2020-11-05 14:12 UTC, fspot commented on server/tests/steps/test_percentage.py
> +def sample_df():
autant créer le sample_df dans le corps de `test_simple_percentage` puisque cette fixture ne sert qu'1 seule fois

2020-11-06 09:24 UTC, fspot requested changes
small remark

2020-11-06 10:38 UTC, luc-leonard commented on server/tests/steps/test_percentage.py
> +def sample_df():
:+1:

2020-11-06 10:42 UTC, luc-leonard commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2) VQB pandas: percentage step](https://trello.com/c/RejouubJ/1190-2-vqb-pandas-percentage-step)

2020-11-09 11:24 UTC, fspot approved these changes

2020-11-09 14:51 UTC, merged