fix(server): aggregate step can operate on the on columns
ToucanToco/weaverbird pull request #748
Opened 2020-11-17 14:02 UTC by davinov

2020-11-17 14:24 UTC, luc-leonard requested changes

2020-11-17 14:24 UTC, luc-leonard commented on .github/workflows/ci-server.yml
> +      uses: snok/install-poetry@v1.1.1
erreur ? :p

2020-11-17 14:24 UTC, luc-leonard commented on server/weaverbird/steps/aggregate.py
> +        for aggregation in self.aggregations:
cool d'avoir évité le cas particulier pour la 1ere aggregation !

2020-11-17 14:24 UTC, luc-leonard commented on server/weaverbird/steps/aggregate.py
> +        # it is faster this way, than to transform the original df
:100:

2020-11-17 14:38 UTC, davinov commented on .github/workflows/ci-server.yml
> +      uses: snok/install-poetry@v1.1.1
Nope, mais à mettre dans une autre PR

2020-11-17 17:00 UTC, davinov commented
@luc-leonard I've removed the change in the CI config file, thanks to your upstream fix

2020-11-18 08:50 UTC, luc-leonard approved these changes

2020-11-18 08:50 UTC, luc-leonard commented
LGTM !

2020-11-18 08:56 UTC, merged