fix(fillna-step): use empty array as column default and add error when columns length is < 1
ToucanToco/weaverbird pull request #770
Opened 2020-11-30 11:11 UTC by alice-sevin

In previous PR: https://github.com/ToucanToco/weaverbird/pull/648,
We setted the column default value in filterStep equal to 
```
['']
```
So it displayed the value in multiselect as a selected column (because we considered that column was always a string so we included it into an array ).
We add a util **retrieveColumnsFromColumn** to retrieve the columns value based on column (if column is an array, use it directly otherwise add string to an array ).

Also added a minItems validation to schema and tests to validate that columns has at least one item selected

2020-11-30 11:11 UTC, alice-sevin commented
![](https://github.trello.services/images/mini-trello-icon.png) [AS a conceptor, when using the fill na vqb step without selecting any column I want it to work](https://trello.com/c/KgDQVjWC/4461-as-a-conceptor-when-using-the-fill-na-vqb-step-without-selecting-any-column-i-want-it-to-work)

2020-11-30 12:51 UTC, austil requested changes

2020-11-30 12:51 UTC, austil commented on src/components/stepforms/FillnaStepForm.vue
> +
Je serai pas contre un petit commentaire (ou renommages) expliquant pourquoi on a une prop 'column', au singulier, qui peut exister ou non et être un tableau ou non :upside_down_face:

2020-11-30 13:01 UTC, vdestraitt commented on src/components/stepforms/FillnaStepForm.vue
> +
@alice-sevin tu peux garder la doc d'origine [ici](https://github.com/ToucanToco/weaverbird/blob/5578b05d6a74e647a16a4dd27c74008ffd8a49e1/src/components/stepforms/FillnaStepForm.vue#L55) ?

2020-11-30 16:33 UTC, alice-sevin commented on src/components/stepforms/FillnaStepForm.vue
> +
@vdestraitt , mais en fait y avait une erreur de base non? Column est forcément une string ? Je comprends pas pourquoi j'ai des tests et un default dans la codebase avec des arrays, ça m'a totalement perdu. j'aimerais bien qu'on statue sur ce point, c'est toujours une string ou pas pour la rétrocompat (comme dis dans la doc plus haut que tu points ) ? Comme ça on mets quelque chose de cohérent entre la doc et le default parce que là on va encore se re-paumer plus tard.

2020-11-30 17:02 UTC, alice-sevin commented on src/components/stepforms/FillnaStepForm.vue
> +
@austil , j'ai vu avec vincent du coup vu que c'est toujours une string, on met undefined comme default et on garde l'ancienne implem. All good. Je te laisse revérifier les modifs (j'ai rebase) pour voir si c'est good pour toi ?

2020-12-01 09:01 UTC, austil approved these changes
Just what's needed :+1: Perfect !

2020-12-01 09:09 UTC, merged