feat(pipeline): enable to reorder steps using drag and drop
ToucanToco/weaverbird pull request #886
Opened 2021-04-27 17:38 UTC by alice-sevin

Before: Plop nothing!

After:
Important: We don't want user to reorder this steps while deleting mode is active (we retrieve steps to delete based on indexes). So we added a disabled mode on actions when deleting steps

![after](https://user-images.githubusercontent.com/59559689/116286954-1d155a80-a790-11eb-9ae2-f6522011a82b.gif)

2021-04-27 17:39 UTC, alice-sevin commented
![](https://github.trello.services/images/mini-trello-icon.png) [ETQC je peux déplacer des steps du VQB pour les réordonner](https://trello.com/c/leL6oRQz/1932-etqc-je-peux-d%C3%A9placer-des-steps-du-vqb-pour-les-r%C3%A9ordonner)

2021-04-28 14:01 UTC, austil requested changes
C'est quali (comme d'hab quoi) :stuck_out_tongue: 
J'ai mis quelques suggestions, il faut aussi que je prenne le temps de lire les tests en détails et on pourra merge.

2021-04-29 09:02 UTC, alice-sevin commented on src/components/Pipeline.vue
> +  }
Bien vu l'artiste, je corrige

2021-04-29 09:03 UTC, alice-sevin commented on src/components/Pipeline.vue
> +  }
Chipoteur, arrête de chipoter!

2021-04-29 09:04 UTC, alice-sevin commented on src/components/Pipeline.vue
> +  }
Je regarde ça, de base, j'étais même parti pour un simple find de la step bougée, mais j'ai peur qu'on ai des steps qui ai exactement la même signature, je propose que ça fasse l'objet d'une autre PR comme ça ça sera pas noyé dans la masse de cette déjà assez grosse PR

2021-04-29 09:56 UTC, austil approved these changes
Solide ! :green_circle:

2021-04-29 10:00 UTC, merged