feat(FilterEditor): make variables hiddable for column
ToucanToco/weaverbird pull request #905
Opened 2021-05-11 09:16 UTC by andreamouraud

In alerts, we want to add templates only on the value and not the column, this PR adds a variable to hide them for the column only by simply not passing the parameters to the `AutocompleteWidget` if `hideColumnVariables` is true

2021-05-11 09:35 UTC, WilliamGorge requested changes
Merci!

2021-05-11 09:35 UTC, WilliamGorge commented on src/components/stepforms/widgets/FilterSimpleCondition.vue
> +        :variable-delimiters="hideColumnVariables === true ? undefined : variableDelimiters"
```suggestion
        :available-variables="hideColumnVariables ? undefined : availableVariables"
        :variable-delimiters="hideColumnVariables ? undefined : variableDelimiters"
```

2021-05-11 09:35 UTC, WilliamGorge commented on src/components/Popover.vue
> +  z-index: 999;
on met ce z-index pour les alertes right?

je me demande si on devrait pas plutît mettre cetet rêgle dans les alertes via un v-deep.

2021-05-11 10:16 UTC, andreamouraud commented on src/components/Popover.vue
> +  z-index: 999;
je trouvais ça plus simple ici car dans tous les cas on veut qu'il s'affiche non? le `z-index: 2` était un fix justement car il s'affichait pas

2021-05-11 13:31 UTC, austil commented on src/components/Popover.vue
> +  z-index: 999;
je veux bien l'avis de @alice-sevin là dessus, je suis pas 100% au fait de ce mic-mac :wink:

2021-05-11 14:34 UTC, alice-sevin commented on src/components/Popover.vue
> +  z-index: 999;
Je valide pas à 100% qu'on aura pas d'effets de bords de notre côté cependant (y a beaucoup d'occurences), à vérifier aussi côté embed, je crois qu'il avaient des besoin spécifiques

2021-05-11 14:54 UTC, andreamouraud commented on src/components/Popover.vue
> +  z-index: 999;
c'est revert ici et fait sur tucana à la place du coup https://github.com/ToucanToco/weaverbird/pull/905/commits/828efd82ef76daa6a969cbcb508adfba6ea6e16b

2021-05-12 08:32 UTC, WilliamGorge approved these changes

2021-05-12 08:50 UTC, alice-sevin approved these changes

2021-05-12 08:51 UTC, merged