feat(vqb-step): added rename translator step
ToucanToco/weaverbird pull request #969
Opened 2021-08-10 14:47 UTC by Sanix-Darker

# Summary
- Added the `rename` step in sql_translator.
- Wrote tests of `translate_rename`.

# Checks
- [x] Unit tests

2021-08-10 14:49 UTC, Sanix-Darker commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Snowflake SQL VQB] - Rename Column Step (2)](https://trello.com/c/5wfRqFUr/1116-snowflake-sql-vqb-rename-column-step-2)

2021-08-11 07:43 UTC, f-bb-toucantoco requested changes

2021-08-11 07:43 UTC, f-bb-toucantoco commented on server/weaverbird/backends/sql_translator/steps/rename.py
> +def translate_rename(
L'ajout d'un log pour dire qu'on traite cette step avec les paramètres d'entrée et la sortie serait pratique dans le cas on rencontre des soucis dans le futur

2021-08-11 07:43 UTC, f-bb-toucantoco commented on server/weaverbird/backends/sql_translator/steps/rename.py
> +        f""" (SELECT {', '.join([f'{old} AS {new}' for old, new in step.to_rename])}"""
Il me semble que tu perds l'ensemble des autres colonnes.
Si tu as `SELECT tata, titi FROM my_table` et que tu souhaite renommer tata en toto,
La transformation va donner `SELECT tata as toto FROM my_table`
Cela devrait donner `SELECT tata AS toto, titi FROM my_table`

2021-08-11 09:09 UTC, f-bb-toucantoco commented on server/weaverbird/backends/sql_translator/steps/rename.py
> +    log.info(
change info to debug ;)

2021-08-11 09:09 UTC, f-bb-toucantoco commented on server/weaverbird/backends/sql_translator/steps/rename.py
> +    log.info(
change info to debug ;)

2021-08-11 09:15 UTC, f-bb-toucantoco approved these changes

2021-08-11 09:19 UTC, merged