feat(vqb-step): added if-then-else translator step
ToucanToco/weaverbird pull request #975
Opened 2021-08-12 12:44 UTC by Sanix-Darker

# Summary
- Added the `if-then-else` step in sql_translator.
- Wrote tests of `translate_ifthenelse`.

# Checks
- [x] Unit tests

2021-08-12 12:53 UTC, Sanix-Darker commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2) [Snowflake SQL VQB] - If Then Else Step](https://trello.com/c/Uzmo82cG/1118-snowflake-sql-vqb-if-then-else-step)

2021-08-16 07:35 UTC, f-bb-toucantoco requested changes

2021-08-16 11:12 UTC, Sanix-Darker commented on server/weaverbird/backends/sql_translator/steps/ifthenelse.py
> +    vqb_to_sql = {
Updated

2021-08-16 11:29 UTC, f-bb-toucantoco approved these changes

2021-08-16 13:22 UTC, merged