feat(vqb): added step replace + unit tests
ToucanToco/weaverbird pull request #997
Opened 2021-08-18 13:50 UTC by Sanix-Darker

# What :
- vqb updates
    - added replace step

2021-08-18 14:04 UTC, raphaelvignes requested changes
Merci pour cette nouvelle step ! 
Quelques petites remarques pour ma part.

2021-08-18 14:04 UTC, raphaelvignes commented on server/weaverbird/backends/sql_translator/steps/replace.py
> +
Ici c'est pour tester si on veut remplacer un number par un number ? 
Dans ce cas on pourrait utiliser isinstance(float, from_value) non ?

2021-08-18 14:04 UTC, raphaelvignes commented on server/weaverbird/backends/sql_translator/steps/replace.py
> +        selection_query=build_selection_query(query.metadata_manager.tables_metadata, query_name),
Suite aux modifs de cette PR: https://github.com/ToucanToco/weaverbird/pull/996
Il faut mettre à jour les query metadata comme ceci: 
https://github.com/ToucanToco/weaverbird/blob/c77c3e47943fc9e2d09725472d8b0fc8a40aa2ca/server/weaverbird/backends/sql_translator/steps/rename.py#L51

2021-08-18 14:04 UTC, raphaelvignes commented on server/weaverbird/backends/sql_translator/steps/replace.py
> +        f""" (SELECT {complete_fields(columns=[step.search_column], step=step, query=query)},"""
Le param "step" ne sert pas dans cette fonction: 
cf https://github.com/ToucanToco/weaverbird/blob/c77c3e47943fc9e2d09725472d8b0fc8a40aa2ca/server/weaverbird/backends/sql_translator/steps/utils/query_transformation.py#L170 
```suggestion
        f""" (SELECT {complete_fields(columns=[step.search_column], query=query)},"""
```

2021-08-19 07:33 UTC, Sanix-Darker commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) [Snowflake SQL VQB] - Replace Values Step [3]](https://trello.com/c/ANHEboQs/1124-3-snowflake-sql-vqb-replace-values-step-3)

2021-08-19 07:59 UTC, Sanix-Darker commented on server/tests/steps/sql_translator/test_replace.py
> +    assert query.selection_query == 'SELECT toto, raichu, florizarre FROM REPLACE_STEP_1'
updated !

2021-08-19 07:59 UTC, Sanix-Darker commented on server/tests/steps/sql_translator/test_replace.py
> +    assert query.selection_query == 'SELECT toto, raichu, florizarre FROM REPLACE_STEP_1'
updated !

2021-08-19 07:59 UTC, Sanix-Darker commented on server/tests/steps/sql_translator/test_replace.py
> +    assert query.selection_query == 'SELECT toto, raichu, florizarre FROM REPLACE_STEP_1'
updated !

2021-08-19 07:59 UTC, Sanix-Darker commented on server/weaverbird/backends/sql_translator/steps/replace.py
> +        f"query.metadata_manager.tables_metadata: {query.metadata_manager.tables_metadata}\n"
updated !

2021-08-19 07:59 UTC, Sanix-Darker commented on server/weaverbird/backends/sql_translator/steps/replace.py
> +
updated !

2021-08-19 07:59 UTC, Sanix-Darker commented on server/weaverbird/backends/sql_translator/steps/replace.py
> +        f""" (SELECT {complete_fields(columns=[step.search_column], step=step, query=query)},"""
updated !

2021-08-19 08:09 UTC, raphaelvignes requested changes
Merci pour les modifs. 
Encore 2 remarques accessoires et une plus structurante à prendre en compte. 
Merci !

2021-08-19 08:09 UTC, raphaelvignes commented on server/weaverbird/backends/sql_translator/steps/replace.py
> +
Je suis pas sur qu'il faille mettre `search_column.upper()` car on utilisera le nom fournis par l'utilisateur tel quel.

2021-08-19 08:09 UTC, raphaelvignes commented on server/weaverbird/backends/sql_translator/steps/replace.py
> +
Je pense que tu as oublié l'ajout du ELSE dans le CASE WHEN: 
https://docs.snowflake.com/en/sql-reference/functions/case.html 

Par exemple on devrait avoir: 
`'WITH SELECT_STEP_0 AS (SELECT * FROM products), REPLACE_STEP_1 AS (SELECT TOTO, FLORIZARRE, CASE WHEN RAICHU=2 THEN 4 ELSE RAICHU END AS RAICHU FROM SELECT_STEP_0) '`

2021-08-19 08:26 UTC, Sanix-Darker commented on server/weaverbird/backends/sql_translator/steps/replace.py
> +        f"query.metadata_manager.query_metadata: {query.metadata_manager.query_metadata}\n"
updated !

2021-08-19 08:26 UTC, Sanix-Darker commented on server/weaverbird/backends/sql_translator/steps/replace.py
> +
updated !

2021-08-19 08:26 UTC, Sanix-Darker commented on server/weaverbird/backends/sql_translator/steps/replace.py
> +
Good catch !

2021-08-19 09:41 UTC, raphaelvignes approved these changes
Merci pour la prise en compte des remarques !

2021-08-19 10:15 UTC, merged