Allow cumsum multiple columns
ToucanToco/weaverbird pull request #999
Opened 2021-08-19 08:11 UTC by CharlesRngrd

Hi Toucan,

As a conceptor, I need to cumulate multiple columns.
Here is my PR to enable that ;)

Have a nice day,

Charles

2021-12-06 10:07 UTC, davinov reviewed
Thank you for this contrib :+1: 
Here are a few comments, nothing big! Congrats on this new contribution :)

2021-12-06 10:07 UTC, davinov commented on src/lib/translators/mongo.ts
> +    ];
That'll definitly work, but you'll have an easier time converting the `step.valueColumn` into the new syntax and passing into the same logic after.
Something like you did when reading the python pipeline: https://github.com/ToucanToco/weaverbird/pull/999/files#diff-2fddffd5011b87bd7d07cfcd8ab0a50c9eab64afcbeb1a9c90b3fb216671e5a5R18-R20

Unit tests will ensure both cases results are coherent :)

2021-12-06 10:07 UTC, davinov commented on src/lib/labeller.ts
> +    }
It would be nice to add test case here: https://github.com/ToucanToco/weaverbird/blob/master/tests/unit/labeller.spec.ts#L668
for this new case

2021-12-07 16:04 UTC, davinov requested changes
Thanks for the modifications!
I see yet a few things before we can merge:
- a reference to `step.newcolumn` will make the SQL translation fail (see below)
- it's good to have updated the tests, yet we should keep at least one with the legacy syntax to make sure we're not gonna break it later on


You're nearly there :muscle: thanks!

2021-12-14 16:51 UTC, CharlesRngrd commented
@davinov : I updated the tests.
Me vs Pydantic: 1-0 ;)

2022-01-12 16:42 UTC, davinov commented
I've added a few commits and reopoened the PR here: 1246
Thanks for this nice feature :+1:

2022-01-12 16:42 UTC, closed without merging